# Generated by Django 4.1.3 on 2023-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
