# Generated by Django 4.1.3 on 2023-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
