# Generated by Django 4.1.3 on 2023-05-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_otp_student_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
