# Generated by Django 4.1.3 on 2023-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv_completed',
            field=models.BooleanField(default=False),
        ),
    ]
