# Generated by Django 4.1.3 on 2023-06-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_cv_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
