# Generated by Django 4.1.3 on 2023-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
