# Generated by Django 4.1.3 on 2023-06-21 08:41

from django.db import migrations, models
import users.models
import users.validators
from django.conf import settings

def get_default_image():
    default_image_path = settings.DEFAULT_PROFILE_IMAGE_PATH
    with open(default_image_path, 'rb') as f:
        image_data = f.read()
    return image_data

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default=get_default_image, null=True, upload_to='profile_images', validators=[users.validators.validate_file_size]),
        ),
    ]
