# Generated by Django 4.1.3 on 2023-06-21 09:28

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='/career-backend/My_Career_Guidance/default_images/default_profile_image.jpg', null=True, upload_to='profile_images', validators=[users.validators.validate_file_size]),
        ),
    ]
