# Generated by Django 4.1.3 on 2023-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
