# Generated by Django 4.1.3 on 2023-06-21 11:08

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images', validators=[users.validators.validate_file_size]),
        ),
    ]
