# Generated by Django 4.1.3 on 2023-08-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
    ]
