# Generated by Django 4.1.3 on 2023-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_student_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
