# Generated by Django 4.1.3 on 2024-08-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_is_counselor_alter_counselor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselor',
            options={'permissions': [('can_view_counselor', 'Can view counselor'), ('can_edit_counselor', 'Can edit counselor')]},
        ),
        migrations.AlterField(
            model_name='counselor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
