# Generated by Django 4.1.3 on 2024-08-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_counselor_options_alter_counselor_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
