# Generated by Django 4.1.3 on 2024-08-06 12:22

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.UserManager()),
            ],
        ),
    ]
