# Generated by Django 4.1.3 on 2024-08-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver')], default='Silver', max_length=100),
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('payment_method_token', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_token', models.CharField(blank=True, max_length=19, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
