# Generated by Django 4.1.3 on 2024-08-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_stripecustomer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='unique_token',
        ),
    ]
