# Generated by Django 4.1.3 on 2024-08-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_stripecustomer_unique_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscription_id',
        ),
    ]
