# Generated by Django 4.1.3 on 2023-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_action_action_alter_action_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
