# Generated by Django 4.1.3 on 2024-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='countdown',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
