# Generated by Django 4.1.3 on 2024-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='countdown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
