# Generated by Django 4.1.3 on 2024-02-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goal_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
