# Generated by Django 4.1.3 on 2024-11-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_workexperiencequestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiencequestion',
            name='user',
        ),
    ]
