# Generated by Django 4.1.3 on 2024-11-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_student_is_subscribed'),
        ('diary', '0004_remove_workexperiencequestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencequestion',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
