# Generated by Django 4.1.3 on 2024-11-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_student_is_subscribed'),
        ('diary', '0006_alter_workexperiencequestion_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencequestion',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
