# Generated by Django 4.1.3 on 2023-03-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_answer_remove_question_answer_remove_question_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresultdetail',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizresultdetail',
            name='question',
        ),
        migrations.AddField(
            model_name='quizresultdetail',
            name='answer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='education.answer'),
        ),
        migrations.AddField(
            model_name='quizresultdetail',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='education.question'),
        ),
    ]
