# Generated by Django 4.1.3 on 2023-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
