# Generated by Django 4.1.3 on 2023-03-27 07:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_quizresultdetail_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresultdetail',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='education.answer'),
        ),
        migrations.AlterField(
            model_name='quizresultdetail',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='education.question'),
        ),
    ]
