# Generated by Django 4.1.3 on 2023-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_quiz_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='youtube_link',
        ),
    ]
