# Generated by Django 4.1.3 on 2023-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_quiz_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=700, null=True),
        ),
    ]
