# Generated by Django 4.1.3 on 2023-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='youtube_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
