# Generated by Django 4.1.3 on 2024-08-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_setquizlimit_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetQuizLimit',
            new_name='QuizLimit',
        ),
    ]
