# Generated by Django 4.1.3 on 2024-02-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_student_number'),
        ('timetable', '0003_slot_title_alter_slot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
