# Generated by Django 4.1.3 on 2024-02-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_colourcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colourcode',
            old_name='user',
            new_name='student',
        ),
    ]
