# Generated by Django 4.1.3 on 2024-02-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_rename_user_colourcode_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ColourCode',
        ),
    ]
