# Generated by Django 4.1.3 on 2022-11-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectlevel', models.CharField(choices=[('higher', 'Higher'), ('oridinary', 'Oridinary'), ('foundation', 'Foundation')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(blank=True, related_name='subject_level', to='calculator.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.subject')),
            ],
            options={
                'verbose_name_plural': 'Subject Levels',
            },
        ),
    ]
