# Generated by Django 4.1.3 on 2022-11-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlevel',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculator.subject'),
        ),
    ]
