# Generated by Django 4.1.3 on 2022-11-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_subjectlevel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('point', models.IntegerField()),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade', to='calculator.level')),
            ],
            options={
                'verbose_name_plural': 'Subject Grades',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='subject_level', to='calculator.level'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='SubjectLevel',
        ),
    ]
