# Generated by Django 4.1.3 on 2022-11-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_subjectgrade_subject_level_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgrade',
            name='grade',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
