# Generated by Django 4.1.3 on 2023-05-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_cv_completed'),
        ('calculator', '0004_userpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='grades',
            field=models.ManyToManyField(related_name='user_points', to='calculator.subjectgrade'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='levels',
            field=models.ManyToManyField(related_name='user_points', to='calculator.level'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='subjects',
            field=models.ManyToManyField(related_name='user_points', to='calculator.subject'),
        ),
    ]
