# Generated by Django 4.1.3 on 2022-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_subjectgrade_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgrade',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.AddField(
            model_name='subject',
            name='additional_marks',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='is_additional_marks_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
