# Generated by Django 4.1.3 on 2022-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_subjectgrade_options_subject_additional_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='additional_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
