# Generated by Django 4.1.3 on 2023-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_remove_userpoints_levels_remove_userpoints_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
