# Generated by Django 4.1.3 on 2023-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Level5',
            field=models.BooleanField(default='False'),
        ),
    ]
