# Generated by Django 4.1.3 on 2023-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Level5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='apprentice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='level6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='level8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
