# Generated by Django 4.1.3 on 2023-05-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_alter_choice_level5_alter_choice_apprentice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level6',
            name='point',
        ),
        migrations.RemoveField(
            model_name='level8',
            name='point',
        ),
    ]
