# Generated by Django 4.1.3 on 2023-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_remove_level6_point_remove_level8_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='level6',
            name='point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='level8',
            name='point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
