# Generated by Django 4.1.3 on 2023-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_level6_point_level8_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='level8',
            name='order',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
