# Generated by Django 4.1.3 on 2023-08-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_level8_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level8',
            name='order',
        ),
        migrations.AddField(
            model_name='level8',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
