# Generated by Django 4.1.3 on 2024-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_adminlevel5_adminlevel6_adminlevel8_apprentice_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel5',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlevel6',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlevel8',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
