# Generated by Django 4.1.3 on 2024-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_adminlevel5_is_expired_adminlevel6_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel5',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel6',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel8',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='level5',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='level6',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='level8',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
