# Generated by Django 4.1.3 on 2024-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0014_rename_courseinformation_adminlevel5_course_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel5',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='adminlevel6',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='adminlevel8',
            name='order_number',
        ),
        migrations.AddField(
            model_name='adminlevel5',
            name='nfq_level',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel6',
            name='nfq_level',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel8',
            name='nfq_level',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
