# Generated by Django 4.1.3 on 2024-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_remove_adminlevel5_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprentice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('course_information', models.CharField(blank=True, max_length=100, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='adminlevel5',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminlevel5',
            name='college',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel5',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel6',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminlevel6',
            name='college',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel6',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel8',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminlevel8',
            name='college',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='adminlevel8',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
