# Generated by Django 4.1.3 on 2024-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0016_adminapprentice_adminother_alter_adminlevel5_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminapprentice',
            name='course_information',
        ),
    ]
