# Generated by Django 4.1.3 on 2023-03-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('psychometric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychometric.psychometrictest'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
