# Generated by Django 4.1.3 on 2023-03-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='user',
        ),
    ]
