# Generated by Django 4.1.3 on 2023-03-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0002_alter_testresult_score_alter_testresult_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='psychometric.answer')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='psychometric.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychometric.testresult')),
            ],
        ),
    ]
