# Generated by Django 4.1.3 on 2023-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0003_alter_testresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
