# Generated by Django 4.1.3 on 2023-03-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0003_testresultdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresultdetail',
            old_name='ansr',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testresultdetail',
            old_name='ques',
            new_name='question',
        ),
    ]
