# Generated by Django 4.1.3 on 2023-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0004_testtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometrictest',
            name='intro',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
