# Generated by Django 4.1.3 on 2024-01-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0006_studytips_choiceidea_careeridea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeridea',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psychometric.testtype'),
        ),
        migrations.AlterField(
            model_name='choiceidea',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psychometric.testtype'),
        ),
    ]
