# Generated by Django 4.1.3 on 2024-02-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0007_alter_careeridea_type_alter_choiceidea_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometrictest',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
