# Generated by Django 4.1.3 on 2022-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='objective',
            field=models.TextField(max_length=300),
        ),
    ]
