# Generated by Django 4.1.3 on 2023-05-04 09:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='HobbiesandInterests',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
