# Generated by Django 4.1.3 on 2023-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_hobbiesandinterests_alter_cv_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='eircode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
