# Generated by Django 4.1.3 on 2022-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cv', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_juniorcert_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', unique=True),
        ),
        migrations.CreateModel(
            name='JuniorCertTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('1', 'Common'), ('2', 'Higher'), ('3', 'Ordinary')], max_length=1)),
                ('result', models.CharField(choices=[('1', 'HIGHER MERIT'), ('2', 'MERIT'), ('3', 'ACHIEVED'), ('4', 'PARTIALLY ACHIEVED'), ('5', 'NOT GRADED')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
