# Generated by Django 4.1.3 on 2022-11-24 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_is_juniorcert_test_alter_cv_user_juniorcerttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['Python','C++'], size=None),
            preserve_default=False,
        ),
    ]
