# Generated by Django 4.1.3 on 2023-05-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_reference_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.jobtitle'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user_title',
            field=models.CharField(choices=[('1', 'MR'), ('2', 'MRS'), ('3', 'MS')], max_length=1, null=True),
        ),
    ]
