# Generated by Django 4.1.3 on 2023-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_reference_job_title_alter_reference_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current_work',
            field=models.BooleanField(default=False),
        ),
    ]
