# Generated by Django 4.1.3 on 2022-11-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_cv_hobbiesandinterests_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='user',
        ),
        migrations.AddField(
            model_name='reference',
            name='cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
            preserve_default=False,
        ),
    ]
