# Generated by Django 4.1.3 on 2023-03-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cv', '0008_remove_reference_user_reference_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='contactemail',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='contactnumber',
        ),
        migrations.AddField(
            model_name='reference',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='job_title',
            field=models.CharField(choices=[('1', 'PRINCIPLE'), ('2', 'GUIDANCE_COUNSELLOR'), ('3', 'MANAGER'), ('4', 'FOUNDER'), ('5', 'FOREMAN'), ('6', 'TEAM_LEADER')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='organization_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='user_title',
            field=models.CharField(choices=[('1', 'MR'), ('2', 'MRS'), ('3', 'MS')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
