# Generated by Django 4.1.3 on 2023-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_remove_education_year_alter_juniorcerttest_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
