# Generated by Django 4.1.3 on 2023-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_remove_reference_contactemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='position',
        ),
        migrations.AddField(
            model_name='reference',
            name='area_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
