# Generated by Django 4.1.3 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_reference_position_reference_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='job_title',
            field=models.CharField(choices=[('1', 'PRINCIPLE'), ('2', 'GUIDANCE_COUNSELLOR'), ('3', 'MANAGER'), ('4', 'FOUNDER'), ('5', 'FOREMAN'), ('6', 'TEAM_LEADER')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user_title',
            field=models.CharField(choices=[('1', 'MR'), ('2', 'MRS'), ('3', 'MS')], max_length=1),
        ),
    ]
