# Generated by Django 4.1.3 on 2023-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_qualities_options_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='position',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='type',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='type',
        ),
        migrations.AddField(
            model_name='experience',
            name='jobtitle',
            field=models.CharField(choices=[('1', 'ASSISTANT'), ('2', 'WORK SHADOW'), ('3', 'OTHER')], default='other', max_length=1),
        ),
        migrations.AddField(
            model_name='qualities',
            name='quality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
