# Generated by Django 4.1.3 on 2023-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_remove_experience_position_remove_qualities_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='jobtitle',
            field=models.CharField(choices=[('1', 'ASSISTANT'), ('2', 'WORK SHADOW'), ('3', 'OTHER')], max_length=1),
        ),
    ]
