# Generated by Django 4.1.3 on 2023-05-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_address2'),
        ('cv', '0011_skills_skill_dropdown_alter_education_examtaken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='cv',
        ),
        migrations.AddField(
            model_name='qualities',
            name='interest',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
