# Generated by Django 4.1.3 on 2023-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_remove_reference_cv_qualities_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_dropdown',
            field=models.CharField(blank=True, choices=[('1', 'SELF STARTER'), ('2', 'People Skills'), ('3', 'Critical Thinking Skills'), ('4', 'Practical Skills'), ('5', 'Communication Skills'), ('6', 'Teamwork Skills'), ('7', 'Information Skills'), ('8', 'Creative Skills'), ('9', 'Critical Problem Solving')], max_length=2, null=True),
        ),
    ]
