# Generated by Django 4.1.3 on 2023-03-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_experience_jobtitle'),
        ('cv', '0012_jobtitle_alter_reference_job_title'),
    ]

    operations = [
    ]
