# Generated by Django 4.1.3 on 2023-03-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cv', '0013_merge_20230310_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorcerttest',
            name='subject',
            field=models.CharField(choices=[('1', 'ENGLISH'), ('2', 'MATHEMATICS'), ('3', 'IRISH'), ('4', 'ACCOUNTING'), ('5', 'AGRICULTURAL ECONOMICS'), ('6', 'AGRICULTURAL SCIENCE'), ('7', 'ANCIENT_GREEK'), ('8', 'APPLIED MATHEMATICS'), ('9', 'ARABIC'), ('10', 'ART'), ('11', 'BIOLOGY'), ('12', 'BULGARIAN'), ('13', 'BUSINESS'), ('14', 'CHEMISTRY'), ('15', 'CLASSICAL STUDIES'), ('16', 'CONSTRUCTION STUDIES'), ('17', 'CZECH'), ('18', 'DANISH'), ('19', 'DESIGN & COMMUNICATION GRAPHICS'), ('20', 'DUTCH'), ('21', 'ECONOMICS'), ('22', 'ENGINEERING'), ('23', 'ESTONIAN'), ('24', 'FINNISH'), ('25', 'FRENCH'), ('26', 'GEOGRAPHY'), ('27', 'GERMAN'), ('28', 'HEBREW STUDIES'), ('29', 'HISTORY'), ('30', 'HOME ECONOMICS'), ('31', 'HUNGARIAN'), ('32', 'ITALIAN'), ('33', 'JAPANESE'), ('34', 'LATIN'), ('35', 'LATVIAN'), ('36', 'LINK MODULES'), ('37', 'LITHUANIAN'), ('38', 'MALTESE'), ('39', 'MODERN GREEK'), ('40', 'MUSIC'), ('41', 'PHYSICS'), ('42', 'PHYSICS & CHEMISTRY'), ('43', 'POLISH'), ('44', 'POLITICS & SOCIETY'), ('45', 'PORTUGESE'), ('46', 'RELIGIOUS EDUCATION'), ('47', 'ROMANIAN'), ('48', 'RUSSIAN'), ('49', 'SLOVAKIAN'), ('50', 'SLOVENIAN'), ('51', 'SPANISH'), ('52', 'SWEDISH'), ('53', 'TECHNOLOGY')], max_length=2),
        ),
        migrations.CreateModel(
            name='LeavingCertTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('1', 'ENGLISH'), ('2', 'MATHEMATICS'), ('3', 'IRISH'), ('4', 'ACCOUNTING'), ('5', 'AGRICULTURAL ECONOMICS'), ('6', 'AGRICULTURAL SCIENCE'), ('7', 'ANCIENT_GREEK'), ('8', 'APPLIED MATHEMATICS'), ('9', 'ARABIC'), ('10', 'ART'), ('11', 'BIOLOGY'), ('12', 'BULGARIAN'), ('13', 'BUSINESS'), ('14', 'CHEMISTRY'), ('15', 'CLASSICAL STUDIES'), ('16', 'CONSTRUCTION STUDIES'), ('17', 'CZECH'), ('18', 'DANISH'), ('19', 'DESIGN & COMMUNICATION GRAPHICS'), ('20', 'DUTCH'), ('21', 'ECONOMICS'), ('22', 'ENGINEERING'), ('23', 'ESTONIAN'), ('24', 'FINNISH'), ('25', 'FRENCH'), ('26', 'GEOGRAPHY'), ('27', 'GERMAN'), ('28', 'HEBREW STUDIES'), ('29', 'HISTORY'), ('30', 'HOME ECONOMICS'), ('31', 'HUNGARIAN'), ('32', 'ITALIAN'), ('33', 'JAPANESE'), ('34', 'LATIN'), ('35', 'LATVIAN'), ('36', 'LINK MODULES'), ('37', 'LITHUANIAN'), ('38', 'MALTESE'), ('39', 'MODERN GREEK'), ('40', 'MUSIC'), ('41', 'PHYSICS'), ('42', 'PHYSICS & CHEMISTRY'), ('43', 'POLISH'), ('44', 'POLITICS & SOCIETY'), ('45', 'PORTUGESE'), ('46', 'RELIGIOUS EDUCATION'), ('47', 'ROMANIAN'), ('48', 'RUSSIAN'), ('49', 'SLOVAKIAN'), ('50', 'SLOVENIAN'), ('51', 'SPANISH'), ('52', 'SWEDISH'), ('53', 'TECHNOLOGY')], max_length=2)),
                ('level', models.CharField(choices=[('1', 'HIGHER MERIT'), ('2', 'MERIT'), ('3', 'ACHIEVED'), ('4', 'PARTIALLY ACHIEVED'), ('5', 'NOT GRADED')], max_length=1)),
                ('result', models.CharField(choices=[('1', 'HIGHER MERIT'), ('2', 'MERIT'), ('3', 'ACHIEVED'), ('4', 'PARTIALLY ACHIEVED'), ('5', 'NOT GRADED')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
