# Generated by Django 4.1.3 on 2023-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_alter_skills_skill_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
