# Generated by Django 4.1.3 on 2023-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_experience_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
