# Generated by Django 4.1.3 on 2023-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_alter_juniorcerttest_subject_leavingcerttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorcerttest',
            name='level',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Higher'), ('3', 'Ordinary')], max_length=2),
        ),
        migrations.AlterField(
            model_name='juniorcerttest',
            name='result',
            field=models.CharField(choices=[('1', 'HIGHER MERIT'), ('2', 'MERIT'), ('3', 'ACHIEVED'), ('4', 'PARTIALLY ACHIEVED'), ('5', 'NOT GRADED')], max_length=2),
        ),
        migrations.AlterField(
            model_name='leavingcerttest',
            name='level',
            field=models.CharField(choices=[('1', 'HIGHER'), ('2', 'ORDINARY'), ('3', 'COMMON')], max_length=2),
        ),
        migrations.AlterField(
            model_name='leavingcerttest',
            name='result',
            field=models.CharField(choices=[('1', 'PENDING'), ('2', 'H1'), ('3', 'H2'), ('4', 'H3'), ('5', 'H4'), ('6', 'H5'), ('7', 'H6'), ('8', 'H7'), ('9', 'O1'), ('10', 'O2'), ('11', 'O3'), ('12', 'O4'), ('13', 'O5'), ('14', 'O6'), ('15', 'O7')], max_length=2),
        ),
    ]
