# Generated by Django 4.1.3 on 2023-07-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_education_enddate_education_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualities',
            name='quality_dropdown',
            field=models.CharField(blank=True, choices=[('1', 'Intuitive'), ('2', 'Persistent'), ('3', 'Enthusiastic'), ('4', 'Persuasive'), ('5', 'Empathic'), ('6', 'Patient'), ('7', 'A_Good_Listener'), ('8', 'Expressive')], max_length=2, null=True),
        ),
    ]
