# Generated by Django 4.1.3 on 2023-07-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_qualities_quality_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='objective',
        ),
    ]
