# Generated by Django 4.1.3 on 2023-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_remove_cv_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='objective',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
