# Generated by Django 4.1.3 on 2024-01-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_cv_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name_plural': 'Interests'},
        ),
    ]
