# Generated by Django 4.1.3 on 2024-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_remove_skills_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(default='Desc', max_length=300, verbose_name=''),
        ),
    ]
