# Generated by Django 4.1.3 on 2024-01-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_skills_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
    ]
