# Generated by Django 4.1.3 on 2024-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_remove_skills_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(default='desc', max_length=300),
        ),
    ]
