# Generated by Django 4.1.3 on 2024-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
