# Generated by Django 4.1.3 on 2024-01-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0026_alter_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualities',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
