# Generated by Django 4.1.3 on 2024-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0027_alter_qualities_description_alter_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='eircode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
