# Generated by Django 4.1.3 on 2024-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_additionalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name_plural': 'additional_info'},
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='additional_info',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
