# Generated by Django 4.1.3 on 2024-01-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_alter_additionalinfo_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorcerttest',
            name='level',
            field=models.CharField(blank=True, choices=[('Common', 'Common'), ('2', 'Higher'), ('3', 'Ordinary')], max_length=112, null=True),
        ),
        migrations.AlterField(
            model_name='juniorcerttest',
            name='result',
            field=models.CharField(blank=True, choices=[('HIGHER MERIT', 'Highermerit'), ('MERIT', 'Merit'), ('3', 'ACHIEVED'), ('4', 'PARTIALLY ACHIEVED'), ('5', 'NOT GRADED')], max_length=112, null=True),
        ),
    ]
