# Generated by Django 4.1.3 on 2024-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0032_alter_juniorcerttest_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorcerttest',
            name='level',
            field=models.CharField(blank=True, choices=[('Common', 'Common'), ('Higher', 'Higher'), ('Ordinary', 'Ordinary')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juniorcerttest',
            name='result',
            field=models.CharField(blank=True, choices=[('HIGHER MERIT', 'Highermerit'), ('MERIT', 'Merit'), ('ACHIEVED', 'Achieved'), ('PARTIALLY ACHIEVED', 'Partiallyachieved'), ('NOT GRADED', 'Notgraded')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leavingcerttest',
            name='level',
            field=models.CharField(choices=[('HIGHER', 'Higher'), ('ORDINARY', 'Ordinary'), ('COMMON', 'Common')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leavingcerttest',
            name='result',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('H6', 'H6'), ('H7', 'H7'), ('O1', 'O1'), ('O2', 'O2'), ('O3', 'O3'), ('O4', 'O4'), ('O5', 'O5'), ('O6', 'O6'), ('O7', 'O7')], max_length=255),
        ),
    ]
