# Generated by Django 4.1.3 on 2024-01-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0033_alter_juniorcerttest_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juniorcerttest',
            options={'verbose_name_plural': 'junior_cert_test'},
        ),
    ]
