# Generated by Django 4.1.3 on 2024-01-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0034_alter_juniorcerttest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juniorcerttest',
            options={},
        ),
        migrations.AlterField(
            model_name='leavingcerttest',
            name='level',
            field=models.CharField(choices=[('Common', 'Common'), ('Higher', 'Higher'), ('Ordinary', 'Ordinary')], max_length=255),
        ),
    ]
