# Generated by Django 4.1.3 on 2024-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_alter_additionalinfo_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
