# Generated by Django 4.1.3 on 2024-02-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0038_alter_cv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='additional_info',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cv',
            name='HobbiesandInterests',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='objective',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualities',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualities',
            name='interest',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
