# Generated by Django 4.1.3 on 2024-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0039_alter_additionalinfo_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interests',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='juniorcerttest',
            name='result',
            field=models.CharField(blank=True, choices=[('HIGHER MERIT', 'Highermerit'), ('MERIT', 'Merit'), ('ACHIEVED', 'Achieved'), ('PARTIALLY ACHIEVED', 'Partiallyachieved'), ('NOT GRADED', 'Notgraded'), ('DISTINCTION', 'Distinction')], max_length=255, null=True),
        ),
    ]
